server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini-magazine
    username: postgres
    password: 123

  jpa:
    hibernate:
      #      ddl-auto: create
             ddl-auto: update
    show-sql: true